use strict;
use warnings;
no warnings qw(redefine);

1;

# this class is AUTOGENERATED and will be AUTOMATICALLY REGENERATED
# all work done in this module will be LOST


package SchedulerDB::JOB;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		ID => [ DB_SCALAR, undef, 0, undef ],
		FINISHED => [ DB_SCALAR, undef, 0, undef ],
		EXCLUSIVEKEY => [ DB_SCALAR, undef, 0, undef ],
		QUEUE => [ DB_SCALAR, undef, 0, "-1" ],
		STATUS => [ DB_SCALAR, undef, 0, "unknown" ],
		START => [ DB_SCALAR, undef, 0, undef ],
		PRIORITY => [ DB_SCALAR, undef, 0, "3" ],
		PROCESSID => [ DB_SCALAR, undef, 0, "0" ],
		COMMAND => [ DB_SCALAR, undef, 1, undef ],
		STATE => [ DB_SCALAR, undef, 0, "0" ],
		QUEUETIME => [ DB_SCALAR, undef, 1, undef ],
		USER => [ DB_SCALAR, undef, 0, "unknown" ],
	};
}

sub unique_indices {
     return 
		[
			[ "ID" ],
		];
}

sub indices {
     return 
		[
			[ "PRIORITY" ],
			[ "PROCESSID" ],
			[ "QUEUE" ],
			[ "USER" ],
		];
}

1;

package SchedulerDB::QUEUE;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		ID => [ DB_SCALAR, undef, 0, undef ],
		NAME => [ DB_SCALAR, undef, 1, undef ],
		MAXPROCESSES => [ DB_SCALAR, undef, 0, "-1" ],
		TYPE => [ DB_SCALAR, undef, 0, "QSUB" ],
	};
}

sub unique_indices {
     return 
		[
			[ "ID" ],
			[ "NAME" ],
		];
}

sub indices {
     return 
		[
		];
}

1;
